### ISSUE TITLE
Request for new version

### ISSUE THREAD

**Issue by y2sarakawa** [timescale/pg_prometheus#10]
It has been a while since timescale/timescaledb:0.9.2 was released.

I have been using Docker image created with Dockerfile modified several lines for about 3 weeks and seems to be working well.
Like this:
```
FROM postgres:10.4-alpine

ENV PG_MAJOR 10.4
ENV TIMESCALEDB_VERSION 0.9.2
```

I am happy that pg_prometheus follows timescaledb:0.9.2.

**Comment by niksajakovljevic** [comment]
Hi @y2sarakawa, I've created a PR for this https://github.com/timescale/pg_prometheus/pull/18 
Soon we plan to release a new version with significant performance improvements so keep an eye on the repo ;)

**Comment by y2sarakawa** [comment]
#12(, #18), and #19 resolved this issue.
