### ISSUE TITLE
Not able to write metrics on remote postgres database

### ISSUE THREAD

**Issue by maneavinash** [timescale/pg_prometheus#11]
Hi
We are trying to set up Prometheus-Postgres on different machines where we want Prometheus on one machine and Postgres Database on another machine and trying to monitor third  machine by using Node exporter. but we are failing to do so, Could anyone please suggest way forward to write the prometheus
data on different machine in postgres Database. Thanks in advance.

**Comment by niksajakovljevic** [comment]
Hi @maneavinash ,

recently I've published a blog post on how you run Prometheus with PostgreSQL/TimescaleDB:
https://blog.timescale.com/sql-nosql-data-storage-for-prometheus-devops-monitoring-postgresql-timescaledb-time-series-3cde27fd1e07
There is also a tutorial:
http://docs.timescale.com/v0.10/tutorials/prometheus-adapter
