### ISSUE TITLE
Request for correction of the exception message

### ISSUE THREAD

**Issue by y2sarakawa** [timescale/pg_prometheus#15]
https://github.com/timescale/pg_prometheus/blob/c3bf029dfba982c4d4e8c5e327ce7c213ff10200/sql/prometheus.sql#L163

I found a wrong exception message in the function prometheus.insert_view_sample().

My suggestion is like this ...
```
        RAISE EXCEPTION 'insert_view_sample requires 1 parameter';
```

**Comment by niksajakovljevic** [comment]
@y2sarakawa thanks for reporting this. Can you please create a PR to fix this.

**Comment by y2sarakawa** [comment]
@niksajakovljevic Sorry. I have no authority to agree to the CLA on behalf of my organization yet.

Can anyone make a PR?

**Comment by niksajakovljevic** [comment]
No problem. I'll take care of fix it in the next PR.
