### ISSUE TITLE
Use newest Timescaledb version as base image

### ISSUE THREAD

**Issue by bbkgh** [timescale/pg_prometheus#17]
Hi. According to [this issue](https://github.com/timescale/prometheus-postgresql-adapter/issues/19) please update timescaledb base image version to newest one.

**Comment by niksajakovljevic** [comment]
@bbkgh thanks for reporting. I've created a PR https://github.com/timescale/pg_prometheus/pull/18 . We're actively working on performance tuning and we've made significant improvements in write throughput. It should be coming out soon so stayed tuned ;)
