### ISSUE TITLE
implicit declaration of function ‘PG_GETARG_JSONB’; did you mean ‘PG_GETARG_JSONB_P’? [-Wimplicit-function-declaration]   Jsonb    *jb = PG_GETARG_JSONB(3);

### ISSUE THREAD

**Issue by Rajinimaybank** [timescale/pg_prometheus#25]
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -DINCLUDE_PACKAGE_SUPPORT=0 -MMD -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o src/prom.o src/prom.c
src/prom.c: In function ‘prom_construct’:
src/prom.c:407:17: warning: implicit declaration of function ‘PG_GETARG_JSONB’; did you mean ‘PG_GETARG_JSONB_P’? [-Wimplicit-function-declaration]
  Jsonb    *jb = PG_GETARG_JSONB(3);
                 ^~~~~~~~~~~~~~~
                 PG_GETARG_JSONB_P
src/prom.c:407:17: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -DINCLUDE_PACKAGE_SUPPORT=0 -MMD -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o src/parse.o src/parse.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -DINCLUDE_PACKAGE_SUPPORT=0 -MMD -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o src/utils.o src/utils.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -DINCLUDE_PACKAGE_SUPPORT=0 -MMD -shared -o pg_prometheus.so src/prom.o src/parse.o src/utils.o -L/usr/lib/x86_64-linux-gnu  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -L/usr/lib/llvm-6.0/lib  -L/usr/lib/x86_64-linux-gnu/mit-krb5 -Wl,--as-needed
/usr/bin/clang-6.0 -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5 -flto=thin -emit-llvm -c -o src/prom.bc src/prom.c
src/prom.c:407:17: warning: implicit declaration of function 'PG_GETARG_JSONB' is invalid in C99 [-Wimplicit-function-declaration]
        Jsonb      *jb = PG_GETARG_JSONB(3);
                         ^
src/prom.c:407:12: warning: incompatible integer to pointer conversion initializing 'Jsonb *' with an expression of type 'int' [-Wint-conversion]
        Jsonb      *jb = PG_GETARG_JSONB(3);
                    ^    ~~~~~~~~~~~~~~~~~~
2 warnings generated.
/usr/bin/clang-6.0 -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5 -flto=thin -emit-llvm -c -o src/parse.bc src/parse.c
/usr/bin/clang-6.0 -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5 -flto=thin -emit-llvm -c -o src/utils.bc src/utils.c

**Comment by Rajinimaybank** [comment]
Can somebody help me

**Comment by niksajakovljevic** [comment]
Hi @Rajinimaybank 
Do you have PostgreSQL libraries and headers for C installed? https://github.com/timescale/pg_prometheus#requirements
Also make sure that PostgreSQL bin is in your path.
If you run `pg_config` it should print out all the information about installed PostgreSQL version

**Comment by seyhbold** [comment]
This happens to me, too. However when I switched back to postgresql 10 it works fine.

**Comment by josephreynolds** [comment]
I also had this issue. Here is the output of pg_config:
>BINDIR = /usr/lib/postgresql/11/bin
DOCDIR = /usr/share/doc/postgresql-doc-11
HTMLDIR = /usr/share/doc/postgresql-doc-11
INCLUDEDIR = /usr/include/postgresql
PKGINCLUDEDIR = /usr/include/postgresql
INCLUDEDIR-SERVER = /usr/include/postgresql/11/server
LIBDIR = /usr/lib/x86_64-linux-gnu
PKGLIBDIR = /usr/lib/postgresql/11/lib
LOCALEDIR = /usr/share/locale
MANDIR = /usr/share/postgresql/11/man
SHAREDIR = /usr/share/postgresql/11
SYSCONFDIR = /etc/postgresql-common
PGXS = /usr/lib/postgresql/11/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=/usr/include' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=/usr/lib/x86_64-linux-gnu' '--libexecdir=/usr/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--with-icu' '--with-tcl' '--with-perl' '--with-python' '--with-pam' '--with-openssl' '--with-libxml' '--with-libxslt' 'PYTHON=/usr/bin/python' '--mandir=/usr/share/postgresql/11/man' '--docdir=/usr/share/doc/postgresql-doc-11' '--sysconfdir=/etc/postgresql-common' '--datarootdir=/usr/share/' '--datadir=/usr/share/postgresql/11' '--bindir=/usr/lib/postgresql/11/bin' '--libdir=/usr/lib/x86_64-linux-gnu/' '--libexecdir=/usr/lib/postgresql/' '--includedir=/usr/include/postgresql/' '--with-extra-version= (Ubuntu 11.2-1.pgdg18.04+1)' '--enable-nls' '--enable-integer-datetimes' '--enable-thread-safety' '--enable-tap-tests' '--enable-debug' '--enable-dtrace' '--disable-rpath' '--with-uuid=e2fs' '--with-gnu-ld' '--with-pgport=5432' '--with-system-tzdata=/usr/share/zoneinfo' '--with-llvm' '--with-systemd' '--with-selinux' 'MKDIR_P=/bin/mkdir -p' 'TAR=/bin/tar' 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now' '--with-gssapi' '--with-ldap' '--with-includes=/usr/include/mit-krb5' '--with-libs=/usr/lib/mit-krb5' '--with-libs=/usr/lib/x86_64-linux-gnu/mit-krb5' 'build_alias=x86_64-linux-gnu' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security'
CC = gcc
CPPFLAGS = -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/include/mit-krb5
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -L/usr/lib/llvm-6.0/lib -L/usr/lib/x86_64-linux-gnu/mit-krb5 -Wl,--as-needed
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lpthread -lselinux -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -ledit -lrt -lcrypt -ldl -lm
VERSION = PostgreSQL 11.2 (Ubuntu 11.2-1.pgdg18.04+1)

Changing line 407 of prom.c to `Jsonb      *jb = PG_GETARG_JSONB_P(3);` fixed the issue. 
 Relevant details:
https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=4bd1994650fddf49e717e35f1930d62208845974

**Comment by jasonliu--** [comment]
I am getting the same warnings when compiling pg_prometheus against PostgreSQL 11. In addition to the compile-time warnings that the others have posted, when creating a TimescaleDB metrics database in PostgreSQL, I get the following error messages:

```
CREATE EXTENSION IF NOT EXISTS pg_prometheus;
ERROR:  could not load library "/usr/lib/postgresql/11/lib/pg_prometheus.so":
/usr/lib/postgresql/11/lib/pg_prometheus.so: undefined symbol: PG_GETARG_JSONB

GRANT ALL ON SCHEMA prometheus TO prometheus;
ERROR:  schema "prometheus" does not exist

SELECT create_prometheus_table('metrics',use_timescaledb=>true);
ERROR:  function create_prometheus_table(unknown, use_timescaledb => boolean) does not exist
LINE 1: SELECT create_prometheus_table('metrics',use_timescaledb=>tr...
               ^
HINT:  No function matches the given name and argument types.
You might need to add explicit type casts.
```

OS = Debian testing (buster)
PSQL_VERSION = PostgreSQL 11.2 (Debian 11.2-2)

And just like others have reported, when I switch back to PostgreSQL 10, everything works fine with no warning or error messages.

**Comment by josephreynolds** [comment]
@jasonliu-- Are you building from the most recent commit, https://github.com/timescale/pg_prometheus/commit/5afc9dc4a9752384462891c3b3fab160c370b04b?

**Comment by blagojts** [comment]
We have new docker image releases that are built with PG11, thanks to #36. Release v0.2.2 is published
