### ISSUE TITLE
how to create this extension for postgresql manual

### ISSUE THREAD

**Issue by kingfsen** [timescale/pg_prometheus#31]
My company has one postgresql product，I have the username and password, can I use it to create pg_prometheus。I don't want to create myself postgresql with docker。I want to use sql type to create this extension. how can I do it?

**Comment by niksajakovljevic** [comment]
There is installation instruction here https://github.com/timescale/pg_prometheus#installation.
@kinfsen Did you manage to get it up and running?

**Comment by bboule** [comment]
Closing issue based on lapse in response time
