### ISSUE TITLE
Provide new Docker image based on Timescale 1.1.1

### ISSUE THREAD

**Issue by sgama** [timescale/pg_prometheus#33]
The latest image of pg_prometheus available on Dockerhub uses an older version of TimescaleDB.
Would it be possible to push the latest version?

I'm trying to help address the CICD problems as stated here: https://github.com/timescale/pg_prometheus/issues/16

However, I'm running into build errors at the moment regarding Postgres dependencies in an Alpine build environment: https://travis-ci.com/sgama/pg_prometheus/jobs/173339849

**Comment by niksajakovljevic** [comment]
Hi @sgama 
I believe that `latest` docker is using Timescale 1.2. Can you confirm?
It was released a day after you made this comment

**Comment by bboule** [comment]
@sgama where you able to pull the latest?

**Comment by sgama** [comment]
I'm sorry as I do not recall. This was a while ago.
You may close this issue if you'd like. I'll re-open if I run into the same issue when changing backends for Prometheus in the future.
