### ISSUE TITLE
Multiple schema support for pg_prometheus

### ISSUE THREAD

**Issue by irumman** [timescale/pg_prometheus#34]
Hi,

We are try to use pg_prometheus extension segregating each product as a schema. Each schema will hold all set of tables, views, types and functions of pg_prometheus. For example:

> **Schema:** service_a
> Tables: metrics_labels, metrics_values, metrics_copy
> Views: metrics
> **Schema:** service_b
> Tables: metrics_labels, metrics_values, metrics_copy
> Views: metrics
> and so on    
> 

We enabled pg_prometheus extension as superuser in public and then created schema as follows:
```
create schema service_a AUTHORIZATION  prometheus;
grant usage on schema service_a to prometheus;
ALTER DEFAULT PRIVILEGES IN SCHEMA service_a GRANT all privileges ON tables TO prometheus;
ALTER DEFAULT PRIVILEGES IN SCHEMA service_a GRANT all privileges ON functions TO prometheus;
ALTER DEFAULT PRIVILEGES IN SCHEMA service_a GRANT all privileges ON sequences TO prometheus;
ALTER DEFAULT PRIVILEGES IN SCHEMA service_a GRANT all privileges ON types TO prometheus;
set search_path = service_a ,"$user", public;
SELECT create_prometheus_table('metrics');

```
I can see the tables are created under service_a. But during insert, we are getting error that "metrics_labels" not found. Investigating that, we found it is failing in the trigger function "prometheus.insert_view_normal()".

To avoid this problem, we added TG_TABLE_SCHEMA in the trigger function and modified the source of the procedure as below:

```
CREATE OR REPLACE FUNCTION prometheus.insert_view_normal()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
    metric_labels     JSONB = prom_labels(NEW.sample);
    metric_labels_id  INTEGER;
    labels_table      NAME;
    values_table      NAME;
BEGIN
    IF TG_NARGS != 2 THEN
        RAISE EXCEPTION 'insert_view_normal requires 2 parameters';
    END IF;

    values_table := TG_ARGV[0];
    labels_table := TG_ARGV[1];

    -- Insert labels
    EXECUTE format('SELECT id FROM %I.%I l WHERE %L = l.labels AND %L = l.metric_name',
          TG_TABLE_SCHEMA,labels_table, metric_labels, prom_name(NEW.sample)) INTO metric_labels_id;

    IF metric_labels_id IS NULL THEN
      EXECUTE format(
          $$
          INSERT INTO %I.%I (metric_name, labels) VALUES (%L, %L) RETURNING id
          $$,
          TG_TABLE_SCHEMA,
          labels_table,
          prom_name(NEW.sample),
          metric_labels
      ) INTO STRICT metric_labels_id;
    END IF;

    EXECUTE format('INSERT INTO %I.%I (time, value, labels_id) VALUES (%L, %L, %L)',
          TG_TABLE_SCHEMA,values_table, prom_time(NEW.sample), prom_value(NEW.sample), metric_labels_id);

    RETURN NULL;
END
$function$
;
```

```
CREATE OR REPLACE FUNCTION prometheus.insert_view_sample()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
    sample_table      NAME;
BEGIN
    IF TG_NARGS != 1 THEN
        RAISE EXCEPTION 'insert_view_normal requires 2 parameters';
    END IF;

    sample_table := TG_ARGV[0];

    EXECUTE format('INSERT INTO %I.%I (sample) VALUES (%L)',
          TG_TABLE_SCHEMA,sample_table, NEW.sample);

    RETURN NULL;
END
$function$
;
```

Will there be any problem with this setup? If not, can we add these changes to support schema in pg_prometheus?
Please advise.

Thanks.

**Comment by niksajakovljevic** [comment]
Hi @irumman

your approach seems reasonable. Have you tested it? Feel free to create a PR and I'll have a look.
Thanks

**Comment by irumman** [comment]
Yes. I am running it in my dev environment and it's running fine.
Will submit a PR.
Thanks.

**Comment by irumman** [comment]
Hi @niksajakovljevic,

I have started working on this. Is there any pg_prometheus contribution guide line that I should follow?
Please advise.

Thanks.

**Comment by niksajakovljevic** [comment]
Hi @irumman, I'd say just create a PR. Make sure to format your code with: `make pgindent`.
