### ISSUE TITLE
Project status unclear, especially regarding container image releases

### ISSUE THREAD

**Issue by embik** [timescale/pg_prometheus#38]
Hi,

I'm currently investigating potential backends for Prometheus and noticed timescale + pg_prometheus being an option.

However, I'm unsure about the project status. The last release on DockerHub was in January, which correlates with the `0.2.1` release, but isn't up to date with timescaledb releases at all. It's not very clear to me which timescaledb release is going to be included with that image, for example. Tags are very different from the main project releases. The DockerHub page hasn't any documentation too.

Is the Docker image considered actively maintained? Is building it from source with an updated timescaledb version the recommended way for production usage?

**Comment by niksajakovljevic** [comment]
Hey @embik,

sadly it's true that Docker image is behind TimescaleDB releases. There was a lot going on... Anyways, it should be fairly easy to build a Docker image locally. I haven't personally tested it with the latest TimescaleDB but I think it should be fine.

**Comment by embik** [comment]
Hey @niksajakovljevic,

thanks for the clarification, I appreciate it! I'll try what you suggested.
