### ISSUE TITLE
Version inconsistencies

### ISSUE THREAD

**Issue by mike-es** [timescale/pg_prometheus#7]
The versions listed on hub.docker.com (tags), github.com (releases), and in the code itself (Dockerfile) don't seem to line up.

**Docker Hub**
latest/master: pg_prometheus 0.0.1, timescaledb 0.7.0, postgresql 9.6

If pg_prometheus 0.1 is released and stable I would expect "latest" to point to this version.  It seems like this tag wasn't created with the Makefile since latest/master/commit are not updated.

**Github**
latest (only) release: pg_prometheus 0.1 (?), timescaledb 0.8.0, postgresql 10.2

This release seems ok except for the Dockerfile (see next section).

**Dockerfile**
master branch:  pg_prometheus 0.0.1, timescaledb 0.8.0, postgresql 10.2

Even though the latest released version is pg_prometheus 0.1 the Dockerfile has "ENV PG_PROMETHEUS_VERSION 0.0.1"

**Comment by erimatnor** [comment]
@mike-es Thanks for reporting these inconsistencies. I just release v0.2 to fix these issues. Let me know if you still experience issues.

**Comment by bboule** [comment]
@mike-es am closing this out please reach out if you are still having issues.
